### ISSUE TITLE
Publish always returns true (even if the server is unreachable)

### ISSUE THREAD

**Issue by vvzvlad** [tarantool/mqtt#11] opened 2018-04-05 09:53 UTC
Суть: если выполнить mqtt_object:publish при недостижимом сервере (например, остановленном или отключенным от сети), первые несколько минут он все равно вернет true. В аналогичном случае mosquitto_pub некоторое время висит, а потом говорит "Error: Operation timed out" 

Как воспроизвести:
```
local mqtt = require 'mqtt'
mqtt.wb = mqtt.new("id", true)
mqtt.wb:connect({host="host",port=1883,keepalive=60,log_mask=mqtt.LOG_ALL})
--отключаем/останавливаем mqtt-сервер--
local status = mqtt.wb:publish("/topic", "value", mqtt.QOS_1, mqtt.NON_RETAIN)
print(status) --Возвращает "true"
```

**Comment by kostja** [comment] 2018-04-05 10:09
Hi, thank you for your bug report. Care to send us a pull request?

**Comment by cyanide-burnout** [comment] 2018-04-15 08:28
The same issue is here. This doesn't work as expected:
`  local status = connection:publish(topic, data, mqtt.QOS_1, mqtt.NON_RETAIN)
  if not status and
     not connection.connect then
    connection:reconnect()
  end`

**Comment by vvzvlad** [comment] 2018-04-26 19:56
@kostja I do not know how to fix this, so I can not do pull request

**Comment by alg1973** [comment] 2018-05-22 08:31
assigned to @romankhabibov

**Comment by dedok** [comment] 2018-05-28 19:56
@vvzvlad @cyanide-burnout can't reproduce. Can you say OS?

**Comment by dedok** [comment] 2018-05-28 20:08
@vvzvlad can you retest this with the latest master?

**Comment by cyanide-burnout** [comment] 2018-05-28 20:53
Debian 8 x64

**Comment by vvzvlad** [comment] 2018-05-29 10:54
OS: Darwin MBP.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

Found new bug:
```
send status:	true	5
send status:	true	6
send status:	true	7
send status:	true	8
MQTT disconnect  ///Stop broker
send status:	false	The client is not currently connected.
send status:	false	The client is not currently connected.
...
send status:	false	The client is not currently connected.
send status:	false	The client is not currently connected.
send status:	true	29 ///Fake true 
send status:	true	30
send status:	true	31
....
send status:	true	39
MQTT connect   ///Real start broker
send status:	true	40
send status:	true	41
```

**Comment by dedok** [comment] 2018-07-22 11:18
This is an libmosquito issue, and also this behaviour definitely changed after fixes/patches.

So I close this, I guess, that we have to create a new issue, if this will be repeated.

**Closed by dedok** 2018-07-22 11:18 UTC
Labels: bug
